name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push CUDA image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.cuda-11.8
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/stretch-ai_cuda-11.8:latest

    - name: Build and push ROS2 image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.ros2
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/stretch-ai-ros2-bridge:latest

